version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    container_name: backend
    volumes:
      - ./core:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      PG_USER: username
      PG_PASSWORD: password
      PG_NAME: default_database
      PG_HOST: db
      PG_PORT: 5432
      DEBUG: True


      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: mohammadmatin13872008@gmail.com
      EMAIL_HOST_PASSWORD: "vdzvanirtvgsvfmo"
      EMAIL_USE_TLS: "True"
      EMAIL_USE_SSL: "False"
      DOMAIN: 127.0.0.1
      PROTOCOL: http

    ports:
      - "8000:8000"
    depends_on:
      - db
  #  =====================================================================================================================

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

#  =====================================================================================================================
volumes:
  smtp4dev-data:
#  =====================================================================================================================